/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.QuanLyNhanVien;

import DAL.NhanVienController;

import DAL.DBConnect;
import GUI.MenuGUI;
import Models.NhanVien;

import java.util.ArrayList;
import java.util.Set;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.image.*;
import javax.imageio.*;
import java.io.*;
import java.util.Calendar;
import javax.swing.*;

/**
 *
 * @author PC
 */
public class QuanLyNhanVien extends javax.swing.JFrame {

//attributes
    private NhanVienController nhanVienController;
    private String state;
    private ArrayList<NhanVien> listNhanVien;

    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyNhanVien() {
        this.nhanVienController = new NhanVienController();

        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        this.disableAll();
        this.clearAll();
        this.invisibleButton();
        this.displayDataForTableSalary();
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        HeaderPanel = new javax.swing.JPanel();
        panelHeaderBack = new javax.swing.JPanel();
        labelBack = new javax.swing.JLabel();
        panelAdd = new javax.swing.JPanel();
        labelAdd = new javax.swing.JLabel();
        panelHeaderEdit = new javax.swing.JPanel();
        labelEdit = new javax.swing.JLabel();
        labelHeader = new javax.swing.JLabel();
        EmployeeInformationTablePanel = new javax.swing.JPanel();
        labelHearEmp = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelPhone = new javax.swing.JLabel();
        labelBirth = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelPlace = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        labelPosition = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        textPhone = new javax.swing.JTextField();
        textMail = new javax.swing.JTextField();
        textPlace = new javax.swing.JTextField();
        textAddress = new javax.swing.JTextField();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        comboBoxPosition = new javax.swing.JComboBox<>();
        textDay = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textMonth = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textYear = new javax.swing.JTextField();
        SalaryInformationPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelName1 = new javax.swing.JLabel();
        labelName2 = new javax.swing.JLabel();
        labelName4 = new javax.swing.JLabel();
        labelName5 = new javax.swing.JLabel();
        labelName6 = new javax.swing.JLabel();
        textEmployeeId = new javax.swing.JTextField();
        textBaseSalary = new javax.swing.JTextField();
        textBonus = new javax.swing.JTextField();
        textNote = new javax.swing.JTextField();
        labelName7 = new javax.swing.JLabel();
        textCoeff = new javax.swing.JTextField();
        ImagePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textSum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        panelUpdate = new javax.swing.JPanel();
        labelUpdate = new javax.swing.JLabel();
        panelSave = new javax.swing.JPanel();
        labelSave = new javax.swing.JLabel();
        panelCancel = new javax.swing.JPanel();
        labelCancel = new javax.swing.JLabel();
        textDaySalary = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textMonthSalary = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textYearSalary = new javax.swing.JTextField();
        labelName8 = new javax.swing.JLabel();
        comboboxStatus = new javax.swing.JComboBox<>();
        EmployeesTablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSalary = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        textSearch = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        buttonGroupGender.add(radioMale);
        buttonGroupGender.add(radioFemale);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        HeaderPanel.setBackground(new java.awt.Color(0, 0, 0));
        HeaderPanel.setPreferredSize(new java.awt.Dimension(1920, 100));
        HeaderPanel.setLayout(null);

        panelHeaderBack.setBackground(new java.awt.Color(0, 0, 0));

        labelBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelBack.setForeground(new java.awt.Color(255, 255, 255));
        labelBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBack.setText("< Quay Lại");
        labelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelHeaderBackLayout = new javax.swing.GroupLayout(panelHeaderBack);
        panelHeaderBack.setLayout(panelHeaderBackLayout);
        panelHeaderBackLayout.setHorizontalGroup(
            panelHeaderBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelHeaderBackLayout.setVerticalGroup(
            panelHeaderBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBack, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );

        HeaderPanel.add(panelHeaderBack);
        panelHeaderBack.setBounds(0, 0, 170, 112);

        panelAdd.setBackground(new java.awt.Color(0, 0, 0));
        panelAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAddMouseClicked(evt);
            }
        });

        labelAdd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelAdd.setForeground(new java.awt.Color(255, 255, 255));
        labelAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAdd.setText("Thêm mới");

        javax.swing.GroupLayout panelAddLayout = new javax.swing.GroupLayout(panelAdd);
        panelAdd.setLayout(panelAddLayout);
        panelAddLayout.setHorizontalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelAddLayout.setVerticalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        HeaderPanel.add(panelAdd);
        panelAdd.setBounds(880, 0, 195, 100);

        panelHeaderEdit.setBackground(new java.awt.Color(0, 0, 0));
        panelHeaderEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelHeaderEditMouseClicked(evt);
            }
        });

        labelEdit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelEdit.setForeground(new java.awt.Color(255, 255, 255));
        labelEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEdit.setText("Chỉnh sửa");

        javax.swing.GroupLayout panelHeaderEditLayout = new javax.swing.GroupLayout(panelHeaderEdit);
        panelHeaderEdit.setLayout(panelHeaderEditLayout);
        panelHeaderEditLayout.setHorizontalGroup(
            panelHeaderEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelHeaderEditLayout.setVerticalGroup(
            panelHeaderEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        HeaderPanel.add(panelHeaderEdit);
        panelHeaderEdit.setBounds(1100, 0, 180, 100);

        labelHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelHeader.setForeground(new java.awt.Color(255, 204, 51));
        labelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHeader.setText("QUẢN LÝ NHÂN VIÊN");
        HeaderPanel.add(labelHeader);
        labelHeader.setBounds(410, 0, 380, 100);

        EmployeeInformationTablePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelHearEmp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelHearEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHearEmp.setText("Thông tin nhân viên");

        labelGender.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelGender.setText("Giới tính:");

        labelName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelName.setText("Tên Nhân viên:");

        labelPhone.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelPhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPhone.setText("Số điện thoại:");

        labelBirth.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelBirth.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelBirth.setText("Ngày sinh:");

        labelEmail.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEmail.setText("Email:");

        labelPlace.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelPlace.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPlace.setText("Quê quán:");

        labelAddress.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelAddress.setText("Địa chỉ:");

        labelPosition.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelPosition.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPosition.setText("Chức vụ:");

        radioMale.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        radioMale.setText("Nam");

        radioFemale.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        radioFemale.setText("Nữ");

        jLabel2.setText("/");

        jLabel6.setText("/");

        javax.swing.GroupLayout EmployeeInformationTablePanelLayout = new javax.swing.GroupLayout(EmployeeInformationTablePanel);
        EmployeeInformationTablePanel.setLayout(EmployeeInformationTablePanelLayout);
        EmployeeInformationTablePanelLayout.setHorizontalGroup(
            EmployeeInformationTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeInformationTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EmployeeInformationTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeInformationTablePanelLayout.createSequentialGroup()
                        .addComponent(labelHearEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(EmployeeInformationTablePanelLayout.createSequentialGroup()
                        .addGroup(EmployeeInformationTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmployeeInformationTablePanelLayout.createSequentialGroup()
                                .addGroup(EmployeeInformationTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(EmployeeInformationTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textDay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radioMale))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(EmployeeInformationTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(EmployeeInformationTablePanelLayout.createSequentialGroup()
                                        .addComponent(radioFemale)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(EmployeeInformationTablePanelLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textYear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(500, 500, 500))))
                            .addGroup(EmployeeInformationTablePanelLayout.createSequentialGroup()
                                .addGroup(EmployeeInformationTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(EmployeeInformationTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(EmployeeInformationTablePanelLayout.createSequentialGroup()
                                            .addComponent(labelPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(comboBoxPosition, 0, 323, Short.MAX_VALUE))
                                        .addGroup(EmployeeInformationTablePanelLayout.createSequentialGroup()
                                            .addComponent(labelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textAddress))
                                        .addGroup(EmployeeInformationTablePanelLayout.createSequentialGroup()
                                            .addComponent(labelPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textPlace))
                                        .addGroup(EmployeeInformationTablePanelLayout.createSequentialGroup()
                                            .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textMail))
                                        .addGroup(EmployeeInformationTablePanelLayout.createSequentialGroup()
                                            .addComponent(labelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textPhone)))
                                    .addGroup(EmployeeInformationTablePanelLayout.createSequentialGroup()
                                        .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(67, 67, 67))))
        );
        EmployeeInformationTablePanelLayout.setVerticalGroup(
            EmployeeInformationTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeInformationTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHearEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmployeeInformationTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmployeeInformationTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioMale)
                    .addComponent(radioFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmployeeInformationTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(textMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(textYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmployeeInformationTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmployeeInformationTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmployeeInformationTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPlace))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmployeeInformationTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmployeeInformationTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        comboBoxPosition.addItem("Thủ kho");
        comboBoxPosition.addItem("Thu ngân");
        comboBoxPosition.addItem("Quản lý");

        SalaryInformationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông tin lương nhân viên");

        labelName1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelName1.setText("Ngày vào làm:");

        labelName2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelName2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelName2.setText("Mã Nhân viên");

        labelName4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelName4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelName4.setText("Mức lương cơ bản:");

        labelName5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelName5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelName5.setText("Mức lương thưởng:");

        labelName6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelName6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelName6.setText("Ghi chú:");

        textEmployeeId.setEditable(false);

        labelName7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelName7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelName7.setText("Hệ số lương:");

        ImagePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout ImagePanelLayout = new javax.swing.GroupLayout(ImagePanel);
        ImagePanel.setLayout(ImagePanelLayout);
        ImagePanelLayout.setHorizontalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );
        ImagePanelLayout.setVerticalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Tổng lương nhận:");

        textSum.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("VNĐ");

        panelUpdate.setBackground(new java.awt.Color(255, 204, 51));

        labelUpdate.setBackground(new java.awt.Color(255, 255, 0));
        labelUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUpdate.setText("Cập nhật");

        javax.swing.GroupLayout panelUpdateLayout = new javax.swing.GroupLayout(panelUpdate);
        panelUpdate.setLayout(panelUpdateLayout);
        panelUpdateLayout.setHorizontalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelUpdateLayout.setVerticalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelSave.setBackground(new java.awt.Color(51, 204, 0));
        panelSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSaveMouseClicked(evt);
            }
        });

        labelSave.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSave.setText("Lưu");

        javax.swing.GroupLayout panelSaveLayout = new javax.swing.GroupLayout(panelSave);
        panelSave.setLayout(panelSaveLayout);
        panelSaveLayout.setHorizontalGroup(
            panelSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSave, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
        );
        panelSaveLayout.setVerticalGroup(
            panelSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCancel.setBackground(new java.awt.Color(204, 0, 0));

        labelCancel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCancel.setText("Hủy");
        labelCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCancelLayout = new javax.swing.GroupLayout(panelCancel);
        panelCancel.setLayout(panelCancelLayout);
        panelCancelLayout.setHorizontalGroup(
            panelCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
        );
        panelCancelLayout.setVerticalGroup(
            panelCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jLabel7.setText("/");

        jLabel8.setText("/");

        labelName8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelName8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelName8.setText("Trạng thái:");

        comboboxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nghỉ việc", "Đang làm việc", "Nghỉ phép" }));

        javax.swing.GroupLayout SalaryInformationPanelLayout = new javax.swing.GroupLayout(SalaryInformationPanel);
        SalaryInformationPanel.setLayout(SalaryInformationPanelLayout);
        SalaryInformationPanelLayout.setHorizontalGroup(
            SalaryInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalaryInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SalaryInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SalaryInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SalaryInformationPanelLayout.createSequentialGroup()
                            .addGroup(SalaryInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelName6)
                                .addComponent(labelName4)
                                .addComponent(labelName5)
                                .addComponent(labelName1)
                                .addComponent(labelName2))
                            .addGroup(SalaryInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(SalaryInformationPanelLayout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(panelSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(panelCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(panelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(SalaryInformationPanelLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(SalaryInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textBaseSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textNote, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(SalaryInformationPanelLayout.createSequentialGroup()
                                            .addComponent(textBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(labelName7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textCoeff, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(SalaryInformationPanelLayout.createSequentialGroup()
                                            .addComponent(textDaySalary, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textMonthSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textYearSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SalaryInformationPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(textSum, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)))
                                    .addGroup(SalaryInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(SalaryInformationPanelLayout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(ImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(SalaryInformationPanelLayout.createSequentialGroup()
                            .addComponent(labelName8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboboxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        SalaryInformationPanelLayout.setVerticalGroup(
            SalaryInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalaryInformationPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SalaryInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SalaryInformationPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(SalaryInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelName2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SalaryInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textDaySalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(textMonthSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(textYearSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelName1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SalaryInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textBaseSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelName4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SalaryInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelName7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textCoeff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelName5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SalaryInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SalaryInformationPanelLayout.createSequentialGroup()
                                .addComponent(textNote, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(SalaryInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textSum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboboxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelName8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(SalaryInformationPanelLayout.createSequentialGroup()
                                .addComponent(labelName6)
                                .addGap(12, 12, 12)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SalaryInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SalaryInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EmployeesTablePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableSalary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã số nhân viên", "Họ và tên nhân viên", "Giới tính", "Hệ số lương", "Mức lương thưởng", "Mức lương nhận", "Ghi chú", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSalary.setColumnSelectionAllowed(true);
        tableSalary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSalaryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSalary);
        tableSalary.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Danh sách bảng lương nhân viên");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        buttonSearch.setText("Tìm");
        buttonSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSearchMouseClicked(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(255, 0, 102));
        deleteButton.setText("Xóa");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EmployeesTablePanelLayout = new javax.swing.GroupLayout(EmployeesTablePanel);
        EmployeesTablePanel.setLayout(EmployeesTablePanelLayout);
        EmployeesTablePanelLayout.setHorizontalGroup(
            EmployeesTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeesTablePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(EmployeesTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EmployeesTablePanelLayout.createSequentialGroup()
                        .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(deleteButton)))
                .addGap(449, 449, 449))
        );
        EmployeesTablePanelLayout.setVerticalGroup(
            EmployeesTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeesTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EmployeesTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeesTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(deleteButton))
                    .addGroup(EmployeesTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(buttonSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(textSearch, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmployeesTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EmployeeInformationTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SalaryInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmployeeInformationTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SalaryInformationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeesTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableSalaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSalaryMouseClicked
        int index = tableSalary.getSelectedRow();
        showSelectedEmployee(index);
    }//GEN-LAST:event_tableSalaryMouseClicked

    private void panelAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddMouseClicked
        //
        this.state = "Add";
        this.visibleButton();
        this.clearAll();
        this.enableAll();
        tableSalary.setEnabled(false);
    }//GEN-LAST:event_panelAddMouseClicked

    private void panelHeaderEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeaderEditMouseClicked
        if (tableSalary.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn nhân viên muốn chỉnh sửa!");
        } else {
            this.state = "Edit";
            this.visibleButton();
            this.enableAll();
        }
    }//GEN-LAST:event_panelHeaderEditMouseClicked

    private void panelSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSaveMouseClicked
        if (!this.isEmptyField() && this.isValidDate()) {
            int result = JOptionPane.showConfirmDialog(null, "Lưu thay đổi?");
            if (result == JOptionPane.YES_OPTION) {
                NhanVien nhanVien = this.getModel();
                switch (this.state) {
                    case "Add":
                        if (nhanVienController.insert(nhanVien)) {
                            //After add new NhanVien, enable table, set all to uneditable
                            this.displayDataForTableSalary();
                            tableSalary.setEnabled(true);
                            this.disableAll();
                            this.invisibleButton();
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Something went wrong :(");
                        }
                        ;
                        break;
                    case "Edit":
                        if (nhanVienController.update(nhanVien)) {
                            //After edit, enable table, set all to uneditable
                            this.displayDataForTableSalary();
                            tableSalary.setEnabled(true);
                            this.disableAll();
                            this.invisibleButton();
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Something went wrong :(");
                        }
                }
            }
        } else if (this.isEmptyField()) {
            JOptionPane.showMessageDialog(null, "Tên hoặc số điện thoại không được trống!");
        } else {
            JOptionPane.showMessageDialog(null, "Năm sinh không hợp lệ");
        }
    }//GEN-LAST:event_panelSaveMouseClicked

    private void labelCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCancelMouseClicked
        int index = tableSalary.getSelectedRow();
        if (index != -1) {
            this.showSelectedEmployee(index);
            
        } else {
            this.clearAll();
        }
        this.disableAll();
        this.invisibleButton();
        tableSalary.setEnabled(true);
    }//GEN-LAST:event_labelCancelMouseClicked

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        if (tableSalary.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn nhân viên muốn xóa!");
        }
        else{
            int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc sẽ xóa nhân viên này chứ?");
            if (confirm == JOptionPane.OK_OPTION) {
                NhanVien nhanVien = this.getModel();
                nhanVienController.delete(nhanVien);

                this.removeAllElementInTable();
                this.displayDataForTableSalary();
                JOptionPane.showMessageDialog(null, "Xóa thành công!");
            }
        }
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void buttonSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSearchMouseClicked
        String searchString = textSearch.getText().toLowerCase().trim();
        ArrayList<NhanVien> list = nhanVienController.getAllNhanVien();
        this.removeAllElementInTable();

        for (int i = 0; i < list.size(); i++) {
            NhanVien nhanVien = list.get(i);
            String maNhanVien = "" + nhanVien.getMaNhanVien();
            String tenNhanVien = nhanVien.getTenNhanVien().toLowerCase().trim();
            if (maNhanVien.equals(searchString) || tenNhanVien.contains(searchString)) {
                Vector row = new Vector();
                row.add(i + 1);
                row.add(nhanVien.getMaNhanVien());
                row.add(nhanVien.getTenNhanVien());
                row.add(nhanVien.getGioiTinh() == 1 ? "Nam" : "Nu");
                row.add(nhanVien.getHeSoLuong());
                row.add(nhanVien.getLuongThuong());
                row.add(nhanVien.getLuongCoBan() * nhanVien.getHeSoLuong() + nhanVien.getLuongThuong());
                row.add(nhanVien.getGhiChu());

                String trangThai = "";
                switch (nhanVien.getStatusFlag()) {
                    case 0:
                        trangThai = "Nghỉ việc";
                        break;
                    case 1:
                        trangThai = "Đang làm việc";
                        break;
                    default:
                        trangThai = "Nghỉ phép";
                }
                row.add(trangThai);
                //add this row to table
                DefaultTableModel defaultTableModel = (DefaultTableModel) tableSalary.getModel();
                defaultTableModel.addRow(row);
            }
        }
    }//GEN-LAST:event_buttonSearchMouseClicked

    private void labelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackMouseClicked
        new MenuGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_labelBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
////        try {
////            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
////                if ("Nimbus".equals(info.getName())) {
////                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
////                    break;
////                }
////            }
////        } catch (ClassNotFoundException ex) {
////            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (InstantiationException ex) {
////            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (IllegalAccessException ex) {
////            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
////            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        }
//        //</editor-fold>
//
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanVien().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EmployeeInformationTablePanel;
    private javax.swing.JPanel EmployeesTablePanel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JPanel SalaryInformationPanel;
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JComboBox<String> comboBoxPosition;
    private javax.swing.JComboBox<String> comboboxStatus;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAdd;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelBack;
    private javax.swing.JLabel labelBirth;
    private javax.swing.JLabel labelCancel;
    private javax.swing.JLabel labelEdit;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelHearEmp;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelName1;
    private javax.swing.JLabel labelName2;
    private javax.swing.JLabel labelName4;
    private javax.swing.JLabel labelName5;
    private javax.swing.JLabel labelName6;
    private javax.swing.JLabel labelName7;
    private javax.swing.JLabel labelName8;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelPlace;
    private javax.swing.JLabel labelPosition;
    private javax.swing.JLabel labelSave;
    private javax.swing.JLabel labelUpdate;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelCancel;
    private javax.swing.JPanel panelHeaderBack;
    private javax.swing.JPanel panelHeaderEdit;
    private javax.swing.JPanel panelSave;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JTable tableSalary;
    private javax.swing.JTextField textAddress;
    private javax.swing.JTextField textBaseSalary;
    private javax.swing.JTextField textBonus;
    private javax.swing.JTextField textCoeff;
    private javax.swing.JTextField textDay;
    private javax.swing.JTextField textDaySalary;
    private javax.swing.JTextField textEmployeeId;
    private javax.swing.JTextField textMail;
    private javax.swing.JTextField textMonth;
    private javax.swing.JTextField textMonthSalary;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textNote;
    private javax.swing.JTextField textPhone;
    private javax.swing.JTextField textPlace;
    private javax.swing.JTextField textSearch;
    private javax.swing.JTextField textSum;
    private javax.swing.JTextField textYear;
    private javax.swing.JTextField textYearSalary;
    // End of variables declaration//GEN-END:variables

    /**
     * Display data for salary table
     */
    public void displayDataForTableSalary() {
        this.removeAllElementInTable();
        this.listNhanVien = nhanVienController.getAllNhanVien();
        ArrayList<NhanVien> list = this.listNhanVien;
        if (this.listNhanVien != null) {
            DefaultTableModel defaultTableModel = (DefaultTableModel) tableSalary.getModel();
            for (int i = 0; i < this.listNhanVien.size(); i++) {
                NhanVien nhanVien = this.listNhanVien.get(i);

                //create a row and add data
                Vector row = new Vector();
                row.add(i + 1);
                row.add(nhanVien.getMaNhanVien());
                row.add(nhanVien.getTenNhanVien());
                row.add(nhanVien.getGioiTinh() == 1 ? "Nam" : "Nu");
                row.add(nhanVien.getHeSoLuong());
                row.add(nhanVien.getLuongThuong());
                row.add(nhanVien.getLuongCoBan() * nhanVien.getHeSoLuong() + nhanVien.getLuongThuong());
                row.add(nhanVien.getGhiChu());

                String trangThai = "";
                switch (nhanVien.getStatusFlag()) {
                    case 0:
                        trangThai = "Nghỉ việc";
                        break;
                    case 1:
                        trangThai = "Đang làm việc";
                        break;
                    default:
                        trangThai = "Nghỉ phép";
                }
                row.add(trangThai);
                //add this row to table
                defaultTableModel.addRow(row);
            }
        }
    }

    private void showSelectedEmployee(int index) {
        //get selected employee
        NhanVien nhanVien = this.listNhanVien.get(index);

        //retrieve name
        textName.setText(nhanVien.getTenNhanVien());

        //retrieve gender
        if (nhanVien.getGioiTinh() == 1) {
            radioMale.setSelected(true);
        } else {
            radioFemale.setSelected(true);
        }

        //TODO: Fix this
        //retrieve date of birth
        String ngaySinh = nhanVien.getNgaySinh();
        int day = Integer.parseInt(ngaySinh.substring(8, 10));
        int month = Integer.parseInt(ngaySinh.substring(5, 7));
        int year = Integer.parseInt(ngaySinh.substring(0, 4));
        textDay.setText("" + day);
        textMonth.setText("" + month);
        textYear.setText("" + year);
        //retrieve phone
        textPhone.setText("" + nhanVien.getSoDienThoai());

        //retrieve email
        textMail.setText(nhanVien.getEmail());

        //retrieve place
        textPlace.setText(nhanVien.getQueQuan());

        //retrieve address
        textAddress.setText(nhanVien.getDiaChi());

        //retrieve position
        comboBoxPosition.setSelectedItem(nhanVien.getChucVu());

        //retrieve starting day
        String ngayVaoLam = nhanVien.getNgayVaoLam();
        textDaySalary.setText(ngayVaoLam.substring(8, 10));
        textMonthSalary.setText(ngayVaoLam.substring(5, 7));
        textYearSalary.setText(ngayVaoLam.substring(0, 4));

        //retrieve employee id
        textEmployeeId.setText("" + nhanVien.getMaNhanVien());

        //retrieve base salary
        textBaseSalary.setText("" + nhanVien.getLuongCoBan());

        //retrieve bonus salary
        textBonus.setText("" + nhanVien.getLuongThuong());

        //retrieve salary coeff
        textCoeff.setText("" + nhanVien.getHeSoLuong());

        //retrieve note
        textNote.setText(nhanVien.getGhiChu());

        //retrieve status
        switch (nhanVien.getStatusFlag()) {
            case 0:
                comboboxStatus.setSelectedItem("Nghỉ việc");
                break;
            case 1:
                comboboxStatus.setSelectedItem("Đang làm việc");
                break;
            default:
                comboboxStatus.setSelectedItem("Nghỉ phép");
        }

        float tongLuong = nhanVien.getLuongCoBan() * nhanVien.getHeSoLuong() + nhanVien.getLuongThuong();
        textSum.setText("" + tongLuong);
    }

    public void visibleButton() {
        labelSave.setVisible(true);
        labelCancel.setVisible(true);
    }

    public void invisibleButton() {
        labelSave.setVisible(false);
        labelCancel.setVisible(false);
    }

    private void disableAll() {
        //EmpolyeeInfo
        textName.setEditable(false);
        textDay.setEditable(false);
        textMonth.setEditable(false);
        textYear.setEditable(false);
        radioMale.setEnabled(false);
        radioFemale.setEnabled(false);
        textMail.setEditable(false);
        textPhone.setEditable(false);
        textAddress.setEditable(false);
        textPlace.setEditable(false);
        comboBoxPosition.setEnabled(false);

        //Salary Info
//        textEmployeeId.setEditable(false);
        textDaySalary.setEditable(false);
        textMonthSalary.setEditable(false);
        textYearSalary.setEditable(false);
        textBaseSalary.setEditable(false);
        textBonus.setEditable(false);
        textCoeff.setEditable(false);
        textNote.setEditable(false);
        comboboxStatus.setEnabled(false);
    }

    private void enableAll() {
        //EmpolyeeInfo
        textName.setEditable(true);
        textDay.setEditable(true);
        textMonth.setEditable(true);
        textYear.setEditable(true);
        radioMale.setEnabled(true);
        radioFemale.setEnabled(true);
        textPhone.setEditable(true);
        textMail.setEditable(true);
        textAddress.setEditable(true);
        textPlace.setEditable(true);
        comboBoxPosition.setEnabled(true);

        //Salary Info
//        textEmployeeId.setEditable(true);
        textDaySalary.setEditable(true);
        textMonthSalary.setEditable(true);
        textYearSalary.setEditable(true);
        textBaseSalary.setEditable(true);
        textBonus.setEditable(true);
        textCoeff.setEditable(true);
        textNote.setEditable(true);
        comboboxStatus.setEnabled(true);
    }

    private void clearAll() {
        textName.setText("Name");
        textDay.setText("1");
        textMonth.setText("1");
        textYear.setText("1900");
        radioMale.setSelected(false);
        radioFemale.setSelected(false);
        textPhone.setText("12345678");
        textMail.setText("");
        textAddress.setText("");
        textPlace.setText("");
        comboBoxPosition.setSelectedItem("Quản lý");

        //Salary Info
        textEmployeeId.setText("");
        textDaySalary.setText("1");
        textMonthSalary.setText("1");
        textYearSalary.setText("1900");
        textBaseSalary.setText("0");
        textBonus.setText("0");
        textCoeff.setText("1");
        textNote.setText("");
        textSum.setText("0");
        comboboxStatus.setSelectedItem("Đang làm việc");
    }

    public NhanVien getModel() {
        //
        int maNhanVien = 0;
        if (!textEmployeeId.getText().equals("")) {
            maNhanVien = Integer.parseInt(textEmployeeId.getText());
        } else {
            maNhanVien = 0;
        }
        String tenNhanVien = textName.getText();
        String ngaySinhString = textYear.getText() + "-" + textMonth.getText()
                + "-" + textDay.getText();
        /**
         * TODO: Fix this
         */
//        int gioiTinh = buttonGroupGender.getSelection().toString() == "Nam" ? 1 : 0;
        int gioiTinh = radioMale.isSelected() ? 1 : 0;

        int soDienThoai = Integer.parseInt(textPhone.getText());
        String email = textMail.getText();
        String queQuan = textPlace.getText();
        String diaChi = textAddress.getText();
        String chucVu = comboBoxPosition.getSelectedItem().toString();
        String ngayVaoLamString = textYearSalary.getText() + "-" + textMonthSalary.getText() + "-"
                + textDaySalary.getText();
        float HeSoLuong = Float.parseFloat(textCoeff.getText());
        int luongCoBan = Integer.parseInt(textBaseSalary.getText());
        int LuongThuong = Integer.parseInt(textBonus.getText());
        String ghiChu = textNote.getText();
        int status = comboboxStatus.getSelectedIndex();
//        switch (comboboxStatus.getSelectedItem().toString()) {
//            case "Đang làm việc":
//                status = 1;
//                break;
//            case "Nghỉ phép":
//                status = 2;
//                break;
//        }
        //
        NhanVien nhanVien = new NhanVien(maNhanVien, tenNhanVien, ngaySinhString, diaChi, soDienThoai, email, gioiTinh, chucVu, queQuan, ngayVaoLamString, "", "", "", luongCoBan, LuongThuong, HeSoLuong, status, ghiChu);
        return nhanVien;
    }

    private void removeAllElementInTable() {
        DefaultTableModel model = (DefaultTableModel) tableSalary.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
    }

    private boolean isEmptyField() {
        boolean result;
        String name = textName.getText();
        String phone = textPhone.getText();
        //If these field is empty, return true, else return false
        result = name.equals("") && phone.equals("") ? true : false;
        return result;
    }

    private boolean isValidDate() {
        int dobDay = Integer.parseInt(textDay.getText());
        int dobMonth = Integer.parseInt(textMonth.getText());
        int dobYear = Integer.parseInt(textYear.getText());

        int startDay = Integer.parseInt(textDaySalary.getText());
        int startMonth = Integer.parseInt(textMonthSalary.getText());
        int startYear = Integer.parseInt(textYearSalary.getText());
        //If these field is valid, return true, else return false
        if ((dobDay != 0) && (startDay != 0) && (dobMonth != 0) && (startMonth != 0) && (dobYear >= 1000) && (startYear >= 1000)) {
            return true;
        } else {
            return false;
        }
    }
}
